/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: af09f42ba5f355fbbe8fb9b4aa1b87f8)
interface __BaseEnv_Env {
	KV: KVNamespace;
	DATABASE: D1Database;
	BETTER_AUTH_SECRET: string;
	BETTER_AUTH_URL: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "BETTER_AUTH_SECRET" | "BETTER_AUTH_URL">> {}
}
