/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as WorkoutWorkoutIdIndexRouteImport } from './routes/workout/$workoutId/index'
import { Route as WorkoutWorkoutIdExerciseWorkoutExerciseIdRouteImport } from './routes/workout/$workoutId/exercise/$workoutExerciseId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutWorkoutIdIndexRoute = WorkoutWorkoutIdIndexRouteImport.update({
  id: '/workout/$workoutId/',
  path: '/workout/$workoutId/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutWorkoutIdExerciseWorkoutExerciseIdRoute =
  WorkoutWorkoutIdExerciseWorkoutExerciseIdRouteImport.update({
    id: '/workout/$workoutId/exercise/$workoutExerciseId',
    path: '/workout/$workoutId/exercise/$workoutExerciseId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/workout/$workoutId/': typeof WorkoutWorkoutIdIndexRoute
  '/workout/$workoutId/exercise/$workoutExerciseId': typeof WorkoutWorkoutIdExerciseWorkoutExerciseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/workout/$workoutId': typeof WorkoutWorkoutIdIndexRoute
  '/workout/$workoutId/exercise/$workoutExerciseId': typeof WorkoutWorkoutIdExerciseWorkoutExerciseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/workout/$workoutId/': typeof WorkoutWorkoutIdIndexRoute
  '/workout/$workoutId/exercise/$workoutExerciseId': typeof WorkoutWorkoutIdExerciseWorkoutExerciseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/sessions'
    | '/settings'
    | '/api/auth/$'
    | '/workout/$workoutId/'
    | '/workout/$workoutId/exercise/$workoutExerciseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/sessions'
    | '/settings'
    | '/api/auth/$'
    | '/workout/$workoutId'
    | '/workout/$workoutId/exercise/$workoutExerciseId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/sessions'
    | '/settings'
    | '/api/auth/$'
    | '/workout/$workoutId/'
    | '/workout/$workoutId/exercise/$workoutExerciseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SessionsRoute: typeof SessionsRoute
  SettingsRoute: typeof SettingsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  WorkoutWorkoutIdIndexRoute: typeof WorkoutWorkoutIdIndexRoute
  WorkoutWorkoutIdExerciseWorkoutExerciseIdRoute: typeof WorkoutWorkoutIdExerciseWorkoutExerciseIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout/$workoutId/': {
      id: '/workout/$workoutId/'
      path: '/workout/$workoutId'
      fullPath: '/workout/$workoutId/'
      preLoaderRoute: typeof WorkoutWorkoutIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout/$workoutId/exercise/$workoutExerciseId': {
      id: '/workout/$workoutId/exercise/$workoutExerciseId'
      path: '/workout/$workoutId/exercise/$workoutExerciseId'
      fullPath: '/workout/$workoutId/exercise/$workoutExerciseId'
      preLoaderRoute: typeof WorkoutWorkoutIdExerciseWorkoutExerciseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SessionsRoute: SessionsRoute,
  SettingsRoute: SettingsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  WorkoutWorkoutIdIndexRoute: WorkoutWorkoutIdIndexRoute,
  WorkoutWorkoutIdExerciseWorkoutExerciseIdRoute:
    WorkoutWorkoutIdExerciseWorkoutExerciseIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
